name: github-workflows lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: github-workflows lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout shared config
        uses: actions/checkout@v4
        with:
          repository: byteit-ai/github-workflows
          path: .github-workflows
          sparse-checkout: ruff.toml

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check . --config .github-workflows/ruff.toml --output-format=github

      - name: Run Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: format . --check --config .github-workflows/ruff.toml